{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "miku-credit-front.serviceAccountName" . }}
  labels:
{{ include "miku-credit-front.labels" . | nindent 4 }}
{{- end -}}
