apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "subcriptio-muneris.fullname" . }}
  labels:
    {{- include "subcriptio-muneris.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "subcriptio-muneris.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "subcriptio-muneris.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "subcriptio-muneris.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: POSTGRESQL_USERNAME
            valueFrom:
              configMapKeyRef:
                name: subcriptio-muneris-migration-config-map
                key: username
          - name: POSTGRESQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: subcriptio-muneris-migration-config-map
                key: username
          - name: POSTGRESQL_HOST
            valueFrom:
              configMapKeyRef:
                name: subcriptio-muneris-migration-config-map
                key: database-host
          - name: POSTGRESQL_PORT
            valueFrom:
              configMapKeyRef:
                name: subcriptio-muneris-migration-config-map
                key: database-port
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: subcriptio-muneris-migration-secret
                key: password
          - name: KAFKA_URL
            value: kafka.persistance:9092
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /health/rediness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
