apiVersion: batch/v1
kind: Job
metadata:
  name: subcriptio-muneris-migration-job
spec:
  activeDeadlineSeconds: 120
  template:
    spec:
      containers:
        - name: flyway
          image: flyway/flyway
          args:
            - info
            - repair
            - migrate
            - info
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://postgresql.persistance:5432/subcriptiomuneris
            - name: FLYWAY_USER
              value: subcriptiomuneris
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: subcriptio-muneris-migration-secret
                  key: password
          volumeMounts:
            - mountPath: /flyway/sql
              name: sql
      volumes:
        - name: sql
          configMap:
            name: subcriptio-muneris-sql-config-map
      restartPolicy: Never
