{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "subcriptio-muneris.serviceAccountName" . }}
  labels:
{{ include "subcriptio-muneris.labels" . | nindent 4 }}
{{- end -}}
