apiVersion: v1
kind: ConfigMap
metadata:
  name: subcriptio-muneris-sql-config-map
data:
  V1_1__create_table.sql: |
    create table users (
      id serial primary key,
      name varchar(100) not null,
      email varchar(100) not null,
      scoring NUMERIC(5, 2) not null
    );
