apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-config-map
data:
  V1_1__create_user.sql: |
    CREATE USER ${username} WITH
      LOGIN
      NOSUPERUSER
      NOCREATEDB
      NOCREATEROLE
      INHERIT
      NOREPLICATION
      CONNECTION LIMIT -1
      ENCRYPTED PASSWORD '${password}';
  V1_2__create_db.sql: |
    CREATE DATABASE ${username} WITH
      OWNER = ${username}
      ENCODING  = 'UTF8'
      CONNECTION LIMIT = -1;
  V1_3__grant_privileges.sql: |
    GRANT ALL ON DATABASE ${username} TO ${username}
  V1_4__create_table.sql: |
    create table users (
      id serial primary key,
      name varchar(100) not null,
      email integer not null,
      scoring NUMERIC(5, 2) not null
    );
