{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "book-keeper.serviceAccountName" . }}
  labels:
{{ include "book-keeper.labels" . | nindent 4 }}
{{- end -}}
