apiVersion: v1
kind: ConfigMap
metadata:
  name: book-keeper-sql-config-map
data:
  V1_1__create_user.sql: |
    CREATE ROLE ${username} PASSWORD '${password}' LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;
  V1_2__create_db.sql: |
    CREATE DATABASE ${username} WITH OWNER = ${username} ENCODING  = 'UTF8';
  V1_3__grant_privileges.sql: |
    GRANT ALL ON DATABASE ${username} TO ${username}
  V1_4__create_table.sql: |
    create table "loans_types" (
      id serial primary key,
      name varchar(100) not null
    );
    create table loans (
      id serial primary key,
      type_id serial references "loans_types" (id),
      name varchar(100) not null,
      max_length integer not null,
      min_length integer not null,
      max_amount integer not null,
      min_amount integer not null,
      rate NUMERIC(7, 4) not null,
      recuired_scoring NUMERIC(5, 2) not null
    );
  V1_5__insert_data.sql: |
    insert into "loans_types" values (1, 'housing');
    insert into loans values (1, (SELECT id from "loans_types" WHERE name='housing'), 'dream house', 480, 36, 10000000, 100000, 0.035, 60);
